In [ ]:
# import all of the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
# load the dataset
dataset = pd.read_excel('/Folds5x2_pp.xlsx')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [ ]:
# create feature and target variable
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
# divide the dataset into a training and test datasets
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [ ]:
# create the ANN model
ann = tf.keras.models.Sequential()

In [ ]:
# create first dense layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [ ]:
# create second dense layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [ ]:
# create the output layer
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
# compile the model
ann.compile(optimizer='adam',loss = 'mean_squared_error')

In [ ]:
# train the model
ann.fit(x_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 108457.4062
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 399.6946
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 379.1658
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 353.8035
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 325.9858
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 296.5343
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 266.0515
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 235.6227
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 205.4769
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 177.0093
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 150.5323
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

In [ ]:
# predict the output values from the input and display it
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[430.08 431.23]
 [460.92 460.01]
 [464.9  461.14]
 ...
 [471.9  473.26]
 [438.17 438.  ]
 [457.82 463.28]]
